server:
  port: 8443
  ssl:
    key-store: ${SSL_KEY_STORE_PATH}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: ${SSL_KEY_STORE_TYPE}
    key-alias: ${SSL_KEY_ALIAS}
    key-password: ${SSL_KEY_PASSWORD}

spring:
  data:
    mongodb:
      uri: ${MONGO_CONNECTION_STRING}
      database: ${MONGO_DATABASE_NAME}
      auto-index-creation: true
  output:
    ansi:
      enabled: always
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.client.RestTemplateAutoConfiguration

app:
  gpt:
    token: ${GPT_TOKEN}
    organization: ${GPT_ORGANIZATION}
    temperature: ${GPT_TEMPERATURE}
    max-tokens: ${GPT_MAX_TOKENS}
    model: ${GPT_MODEL}
    url: https://api.openai.com/v1/chat/completions
    max-batch-size: ${GPT_MAX_BATCH_SIZE}
    max-history: ${GPT_MAX_HISTORY}
    system-instruction: ${GPT_SYSTEM_INSTRUCTION}
    summarization-instruction: ${GPT_SUMMARIZATION_INSTRUCTION}

  summary-bot:
    username: ${TELEGRAM_USERNAME}
    token: ${TELEGRAM_TOKEN}
    bot-path: ${TELEGRAM_BOT_PATH}
    secret-token: ${TELEGRAM_SECRET_TOKEN}
    accept-message: ${TELEGRAM_ACCEPT_MESSAGE}

  dialogue-bot:
    username: ${DIALOGUE_TELEGRAM_USERNAME}
    token: ${DIALOGUE_TELEGRAM_TOKEN}
    bot-path: ${DIALOGUE_TELEGRAM_BOT_PATH}
    secret-token: ${DIALOGUE_TELEGRAM_SECRET_TOKEN}
    accept-message: ${DIALOGUE_TELEGRAM_ACCEPT_MESSAGE}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
