spring:
  datasource:
    url: jdbc:h2:file:./summary-bot
  flyway:
    validate-migration-naming: true
  output:
    ansi:
      enabled: always

app:
  gpt:
    token: ${GPT_TOKEN}
    organization: ${GPT_ORGANIZATION}
    temperature: ${GPT_TEMPERATURE:0.8}
    model: ${GPT_MODEL:gpt-3.5-turbo}
    url: https://api.openai.com/v1/chat/completions
    max-history: ${GPT_MAX_HISTORY:50}
    system-instruction: Анализ и краткий пересказ сообщений.
    assistant-instruction: Кратко перескажи сообщения. Адаптируй нецензурную лексику и оскорбления в вежливый формат. Минимум лишних сообщений в стиле "пользователь с нимнеймом...". Обращайся по никам.

  telegram:
    username: ${TELEGRAM_USERNAME}
    token: ${TELEGRAM_TOKEN}
