name: Build and deploy docker image

on:
  create:
    tags:
      - v*

jobs:

  build:
    if: github.event.ref_type == 'tag'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode and Create p12 File
        run: echo "${{ secrets.BOT_PRIVATE_KEY_BASE64 }}" | base64 -d > cert/keystore.p12

      - name: Get the version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag summary-tg-bot:${{ env.VERSION }}

      - name: Login to Docker Hub using token
        run: echo "${{ secrets.DOCKERHUB_PULL_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_LOGIN }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag summary-tg-bot:${{ env.VERSION }} ${{ secrets.DOCKERHUB_LOGIN }}/summary-tg-bot:${{ env.VERSION }}
          docker push ${{ secrets.DOCKERHUB_LOGIN }}/summary-tg-bot:${{ env.VERSION }}
